#!/usr/bin/env bash
# script transfers a file from our client
args=("$@")

if [[ ${#args[@]} -lt 3 ]]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp "${args[0]}" "${args[2]}@${args[1]}":~/

  if [[ ${#args[@]} -gt 3 ]]; then
    scp -i "${args[3]}" -o StrictHostKeyChecking=no "${args[0]}" "${args[2]}@${args[1]}":~/
  fi
fi
