#!/usr/bin/env bash
# this the full install

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# this will starting nginx service
sudo service nginx start

# this will be allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# the user ownership of website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# this will be Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# this will Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# this will be Restarting nginx
sudo service nginx restart

