#!/usr/bin/env bash
# Update the package lists

echo -e "Updating and doing some minor checks...\n"

# Check and install nginx if not installed
check_and_install() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "    Installing: $1\n"
        sudo apt-get update -y -qq && sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    $1 is already installed.\n"
    fi
}

check_and_install nginx

echo -e "\nSetting up some minor stuff.\n"

# Allow Nginx HTTP traffic on the firewall
sudo ufw allow 'Nginx HTTP'

# Ensure the user has ownership and permissions for the website files
if [ -d "/var/www" ]; then
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
else
    sudo mkdir -p /var/www
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
fi

# Create necessary directories if they don't exist
for dir in /var/www/{html,error}; do
    if ! [ -d "$dir" ]; then
        sudo mkdir -p "$dir"
    fi
done

# Create the index and error pages
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html >/dev/null

# Backup the default Nginx server configuration
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

# Generate the new server configuration
server_config=$(cat <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://th3-gr00t.tk/ permanent;
    }
    error_page 404 /error_404.html;
    location = /error_404.html {
        internal;
    }
}
EOF
)

# Apply the new server configuration
echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default

# Restart Nginx if it's running, or start it if it's not
if ! pgrep -c nginx &> /dev/null; then
    sudo service nginx start
else
    sudo service nginx restart
fi
