#!/usr/bin/env bash
# Update the package lists
sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html

# permissions to allow create files in this directory
sudo chmod -R 755 /var/www

# create an index page
echo 'Hello World!' |sudo tee /var/www/html/index.html

# create webpage for 404
echo "Ceci n'est pas une page" |sudo tee /var/www/html/custom_404.html
SERVER=$(hostname)

SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
		add_header X-Served-By '$SERVER';
                try_files \$uri \$uri/ =404;
        }
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

sudo /etc/init.d/nginx restart
