#!/usr/bin/env bash
# Update the package lists
sudo apt-get update

# Install Nginx web server
sudo apt-get -y install nginx

# Configure the firewall to allow HTTP traffic on port 80
sudo ufw allow 'Nginx HTTP'

# Create the web content directory
sudo mkdir -p /var/www/html

# Grant permissions to the web content directory
sudo chmod -R 755 /var/www

# Create the index page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create a custom 404 page
echo "this is not a page" | sudo tee /var/www/html/custom_404.html

# Get the hostname of the server
SERVER=$(hostname)

# Configure the Nginx server block
SERVER_CONFIG="
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        add_header X-Served-By '$SERVER';
        try_files \$uri \$uri/ =404;
    }
}"

# Write the server configuration to the default Nginx site
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

# Restart the Nginx service
sudo /etc/init.d/nginx restart
