#!/usr/bin/env bash
# script to install and configure HAproxy on my load balancer

echo -e "Updating & doing some minor checks...\n"

# Check and install nginx if not installed
check_and_install() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "    Installing: $1\n"
        sudo apt-get update -y -qq && sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    $1 is already installed.\n"
    fi
}

sudo apt-get update
sudo apt-get -y install haproxy

# Configure haproxy
cat << EOF |sudo tee -a /etc/haproxy/haproxy.cfg
listen load_balancer
        bind :80
        mode http
        option httpclose
        option forwardfor
        balance roundrobin
        server 434428-web-01 35.153.16.18:80 check
        server 434428-web-02 54.89.135.5:80 check
EOF

# Restart haproxy using init script
sudo /etc/init.d/haproxy restart

# Restart Nginx if it's running, or start it if it's not
if ! pgrep -c nginx &> /dev/null; then
    sudo service nginx start
else
    sudo service nginx restart
fi
