#!/usr/bin/env bash
# This script will  display the messages when receiving signals

echo $$ | sudo tee /var/run/holbertonscript.pid > /dev/null

cleanup() {
    sudo rm /var/run/holbertonscript.pid
    echo 'I hate the kill command'
    exit
}

trap "cleanup" SIGTERM
trap "cleanup" SIGQUIT
trap "echo 'Y U no love me?!'; exit" SIGINT

while true; do
    echo 'To infinity and beyond'
    sleep 2
done
