#!/usr/bin/env bash
# This script will manages manage_my_process

if [ $# -gt 0 ]; then
    case "$1" in
        "start")
            ./manage_my_process &
            echo "$!" > /var/run/my_process.pid
            echo "manage_my_process started"
            ;;
        "stop")
            echo "manage_my_process stopped"
            kill "$(cat /var/run/my_process.pid)"
            rm -f /var/run/my_process.pid
            ;;
        "restart")
            echo "manage_my_process stopped"
            kill "$(cat /var/run/my_process.pid)"
            rm -f /var/run/my_process.pid
            ./manage_my_process &
            echo "$!" > /var/run/my_process.pid
            echo "manage_my_process restarted"
            ;;
        *)
            echo "Usage: manage_my_process {start|stop|restart}"
            ;;
    esac
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
