#!/usr/bin/env bash
# This script will manages manage_my_process

while true; do
    echo "Enter a command (start, stop, restart):"
    read command

    if [ "$command" == "start" ]
    then
	    ./manage_my_process &
	    touch /var/run/my_process.pid
	    echo "$!" > /var/run/my_process.pid
	    echo "manage_my_process started"
	    break
    elif [ "$command" == "stop" ]
    then
	    echo "manage_my_process stopped"
	    kill "$(cat /var/run/my_process.pid)"
	    rm -f /var/run/my_process.pid
	    break
    elif [ "$command" == "restart" ]
    then
	    echo "manage_my_process restarted"
	    kill "$(cat /var/run/my_process.pid)"
	    rm -f /var/run/my_process.pid
	    ./manage_my_process &
	    touch /var/run/my_process.pid
	    echo "$!" > /var/run/my_process.pid
	    break
    else
	    echo "Invalid command. Please enter start, stop, or restart."
    fi
done
