#!/usr/bin/env bash
# This script will displays infinity and beyond indefinitely.
# with a sleep 2  iteration

trap 'echo "I am invincible!!!"' SIGTERM

while :
do
    for ((i=0; ; i++))
    do
        echo "To infinity and beyond"
        sleep 2
    done
done
