#!/usr/bin/env bash
# This script displays # from 1 to 100.

time=1
while (( time <= 100 )); do
    if (( time % 15 == 0 )); then
        echo 'FizzBuzz'
    elif (( time % 3 == 0 )); then
        echo 'Fizz'
    elif (( time % 5 == 0 )); then
        echo 'Buzz'
    else
        echo $time
    fi
    (( time++ ))
done

unset time
