#!/usr/bin/env bash
# This script displays # from 1 to 100.

i=1
while (( i <= 100 )); do
    if (( i % 15 == 0 )); then
        echo 'FizzBuzz'
    elif (( i % 3 == 0 )); then
        echo 'Fizz'
    elif (( i % 5 == 0 )); then
        echo 'Buzz'
    else
        echo $i
    fi
    (( i++ ))
done

unset i
