#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd with a story.

while IFS=: read -r username password user_id group_id user_info home_dir command; do
    echo -n "The user $username is part of the $group_id gang, "
    echo -n "lives in $home_dir and rides $command. "
    echo -n "$user_id's place is protected by the passcode $password, "
    echo "more info about the user here: $user_info"
done < "/etc/passwd"
