#!/usr/bin/env bash
# This script displays "Best School" 10 times

time=1
while [ $time -le 10 ]
do
    echo "Best School"
    if [[ "$time" == '9' ]]
    then
        echo "Hi"
    fi
    ((time++))
done
