#!/usr/bin/env bash
# This script will be displaying "Best School" 10 times

time=1
while [ $time -le 10 ]
do
    if [[ $time == '4' ]]
    then
        echo "bad luck"
    elif [[ $time == '8' ]]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((time++))
done
