#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

counter=1
for ((counter=1; counter<=10; counter++))
do
    if [[ $counter == '4' ]]
    then
        echo "bad luck"
    elif [[ $counter == '8' ]]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
done
