#!/usr/bin/env bash
# this script displays numbers from 1 to 20 and functions

time=1

while [ $time -le 20 ]
do
  echo "$time"
  case $time in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( time++ ))
done
