#!/usr/bin/env bash
# This script that displays the time for 12 hours and 59 minutes

hour=0
if [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute=1
    if [ $minute -le 59 ]
    do
        echo $minute
        ((minute++))
    done
    ((hour++))
done
