#!/usr/bin/env bash
# This script that displays the time for 12 hours and 59 minutes

time=0;
while (( time < 13 ));
do
echo 'Hour:' $time
times=1;
while (( times < 60 ));
do
echo $j; ((times++));
done
((time++)); done
unset time; unset times
