#!/usr/bin/env bash
# This script that displays the time for 12 hours and 59 minutes

i=0
while (( i < 13 )); do
  echo "Hour: $i"
  j=1
  while (( j < 60 )); do
    echo $j
    ((j++))
  done
  ((i++))
done
unset i
unset j

