#!/usr/bin/env bash
# This script shows information about school file.

if [[ -e "$FILE" ]]; then
    echo "$FILE exists."
    
    if [[ -s "$FILE" ]]; then
        echo "$FILE is not empty."
    else
        echo "$FILE is empty."
    fi
    
    if [[ -f "$FILE" ]]; then
        echo "$FILE is a regular file."
    fi
else
    echo "$FILE does not exist."
fi
